dist: bionic
language: node_js

node_js:
  - "12"

script:
  - set -e
  - npm test
  - make docker-test

jobs:
  include:
    - stage: Testing
      name: Node test
    - name: Chrome test
      env: TEST_BROWSER=chrome
      addons:
        chrome: stable
    - name: Firefox test
      env: TEST_BROWSER=firefox
      addons:
        firefox: latest
    - stage: Release
      name: NPM release
      script: npm run build
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_API_KEY'
        skip_cleanup: true
        on:
          branch: master
          tags: true
          condition: type != pull_request
